### ISSUE TITLE
Desafio aula DIO

### ISSUE THREAD

**Issue by SergioDevSousa** [alinealien/resolvendo-codigos-py-copilot#12]
Não encontrei o link do repositório pra realizar o fork na aula. Seria interessante adicionar o link do repositório para facilitar onde fazer o fork. Eu consegui porque visualizei o nome do repositório no vídeo da aula.

**Comment by alinealien** [comment]
> Não encontrei o link do repositório pra realizar o fork na aula. Seria interessante adicionar o link do repositório para facilitar onde fazer o fork. Eu consegui porque visualizei o nome do repositório no vídeo da aula.

Olá, obrigada pela mensagem! Irei adicionar o link do repo nos materiais de apoio/complementares da plataforma. Agradeço pelo feedback! Bons estudos! 🎉😁
